== Les principes (Introduction)

Avant de se lancer dans la création d’un modèle, il convient de bien comprendre, la « philosophie » de MAGEO, c’est-à-dire le cadre conceptuel sur lequel reposent  toutes les manipulations qu’on peut faire.

=== L'objectif général

Notre objectif est de développer une plateforme orientée vers les besoins des chercheurs en sciences humaines, proposant en particulier un cadre adapté au développement de modèles spatialisés. A travers les mots choisis dans les dialogues, les structures proposées, la documentation, nous avons cherché à définir un contexte intellectuel qui soit dégagé le plus possible de toute technique informatique. Nous avons voulu aussi définir des entités conceptuelles associées à des formes graphiques explicites permettant de construire un modèle simple à comprendre et dont la combinatoire soit riche de possibilités. Ceci se traduit par le méta-modèle AOC, pour Agent – Organisation – Comportement, décrit dans (Langlois, 2010, 2014). Ce méta-modèle s’inscrit à la fois dans la théorie des systèmes complexes, de l’approche distribuée, individus-centrée et des systèmes multi-agents (Varenne, 2011), qui offrent une approche transdisciplinaire pouvant être utilisée dans les différentes disciplines des sciences humaines.

===   Le principe méthodologique de base : l’intégration du processus de modélisation.

La construction d’un modèle commence en général par la réalisation d’un *modèle conceptuel* qui permet de définir *l’ontologie* du modèle, principalement ses entités fondamentales ebt leurs relations. Cette étape est classiquement représentée par différents schémas, dans le cadre d’une méthodologie de conception, par exemple en UML (Unified Modeling Langage). Ce niveau conceptuel étant validé, on construit le modèle définitif dans un autre cadre technique, par exemple en le programmant dans un langage informatique selon les spécifications définies par le modèle conceptuel. On obtient alors un modèle de simulation comme une application exécutable sur un ordinateur. Bien souvent, l’application développée est très éloignée du modèle conceptuel initial, parce qu’ils sont issus de contextes techniques très différents : un schéma UML et un programme en Java par exemple. De plus le modèle final est souvent réalisé par d’autres personnes que les concepteurs initiaux, la logique de départ est alors noyée dans une forêt de détails techniques, de choix de variables, de structures, de paramètres cachés, d’algorithmes. Si bien qu’il est parfois difficile de vérifier l’adéquation entre le modèle conceptuel et le modèle de simulation et qu’il est compliqué de rendre le modèle reproductible, pour pouvoir le faire vérifier, valider ou adapter par d’autres équipes, ce qui est pourtant un critère de scientificité important.

Dans MAGéo, les trois phases – conception, développement, fonctionnement – sont totalement intégrées. Ceci permet une simplification considérable du processus de réalisation d’un modèle, ainsi qu’une grande lisibilité du modèle final, puisque l’on peut descendre progressivement dans les détails du modèle conceptuel, à partir de sa représentation graphique, contrairement à un modèle entièrement codé dans un langage de programmation. Néanmoins, cette intégration masque deux niveaux de réalisation qu’il importe de comprendre afin d’éviter toute confusion.

*Le niveau conceptuel* est celui de l’ontologie du modèle où les entités sont abordées au niveau abstrait. Par exemple, un agent n’est ici qu’une notion abstraite qui ne décrit pas un objet précis mais définit les propriétés communes à tous les objets de sa « classe ». Le niveau conceptuel définit donc la structuration de l’information des entités d’une classe donnée, mais ne définit pas les valeurs à stocker dans chacune de ces entités.

*Le niveau physique* est celui de la simulation proprement dite du modèle, de son exécution, de son fonctionnement. Ce modèle physique s’inscrit dans le temps. Pour spécifier qu’un agent est considéré à ce niveau, on parlera donc *d’agent physique*. Pour passer du niveau conceptuel au niveau physique, deux opérations sont nécessaires. *L’instanciation* qui crée en mémoire, pour chaque classe d’entité, une collection d’entités individualisées à partir des informations propres à sa classe. *L’initialisation* qui renseigne pour $$t = t_0$$ (l’instant initial), les différentes variables d’état et la géométrie des entités instanciées. Le système est alors dans son état initial, prêt à évoluer dans le temps. Ainsi un agent physique d’une certaine classe possède un état qui s’inscrit dans l’espace, la matière et le temps de la simulation du modèle
